apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-udqc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-udqc
    app.kubernetes.io/part-of: build-suite-test-application-jtxy
  name: devfile-sample-hello-world-udqc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-udqc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-udqc
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-vdei-tenant/build-suite-test-application-jtxy/devfile-sample-hello-world-udqc@sha256:dec705736a64db85a64b74a7dbd28ba627f0ca6a7683732bba907fb067905375
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
